#!/bin/sh
#
# Initialize HCFW
#

case "$1" in
  start)
    echo "Starting HCFW..."
    echo "Hello HCFW world!"
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;

  stop)
    echo "Stopping HCFW..."
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;

  restart|reload)
    "$0" stop
    "$0" start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
